Modifi collab
2019-d05-code/gestion-des-missions-back pull request #19
Opened 2019-05-24 15:46 UTC by gspaul6

2019-05-24 16:06 UTC, ESPYMyDung submitted a review, later dismissed

2019-05-24 16:11 UTC, ESPYMyDung submitted a review, later dismissed

2019-05-26 14:53 UTC, Tahrky requested changes
Problêmes avec Jenkins, corrigé avant approbation !
Problems with Jenkins, correct them before approval.

2019-05-27 07:46 UTC, Tahrky approved these changes

2019-05-27 07:46 UTC, merged